// Bank database: all German FinTS/PIN-TAN institutes.
//
// Source: banks-data.json, generated by scripts/update-banks.mjs from
// hbci4java's actively maintained blz.properties (with dead hosts rewritten
// to their live successors and legacy alternate URLs preserved as urlAlt).
// Re-run the script to refresh. On top of that we detect a "brand" per bank
// group so the frontend can show a matching logo, and expose a curated list
// of popular banks for quick access.

import fs from 'node:fs';
import path from 'node:path';
import { parseBankQuery } from './bank-query.ts';

export type Brand =
  | 'sparkasse' | 'sparda' | 'psd' | 'vrbank' | 'deutschebank' | 'postbank'
  | 'commerzbank' | 'comdirect' | 'ing' | 'dkb' | 'hypovereinsbank' | 'santander'
  | 'targobank' | 'norisbank' | 'consorsbank' | 'apobank' | 'gls' | 'triodos'
  | 'ethikbank' | 'oldenburgische' | 'degussa' | 'generic';

/** One row of banks-data.json, plus the detected brand. */
export type Institute = {
  blz: string;
  name: string;
  location: string;
  bic: string;
  url: string;
  urlAlt?: string;
  brand: Brand;
};

/**
 * A curated login-screen quick pick. (The approval app a brand's customers
 * use is kept per brand in lib/brands.ts, not here: a bank found by search
 * needs it just as much.)
 */
export type PopularBank = {
  key: string;
  name: string;
  brand: Brand;
  /** Nationwide banks resolve to one BLZ … */
  blz?: string;
  url?: string;
  bic?: string;
  fullName?: string;
  /** … regional groups (Sparkasse, VR, …) hand over to the search instead. */
  search?: string;
};

type RawInstitute = Omit<Institute, 'brand'>;

const raw: RawInstitute[] = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), 'banks-data.json'), 'utf8'),
);

// ---------------------------------------------------------------------------
// Brand detection — used to pick a logo + accent color in the frontend.
// ---------------------------------------------------------------------------
const BRAND_RULES: [Brand, RegExp][] = [
  ['sparkasse', /sparkasse|kreissparkasse|stadtsparkasse|spk\b/i],
  ['sparda', /sparda/i],
  ['psd', /\bpsd\b/i],
  ['vrbank', /volksbank|raiffeisen|vr[- ]?bank|vr bank|spar- ?u\.? ?kredit|budenheim|genossenschaftsbank|verbund|aachener bank|gladbacher bank|k(ö|oe)lner bank|dortmunder volks/i],
  ['deutschebank', /deutsche bank/i],
  ['postbank', /postbank/i],
  ['commerzbank', /commerzbank/i],
  ['comdirect', /comdirect/i],
  ['ing', /\bing[- ]/i],
  ['dkb', /deutsche kreditbank|\bdkb\b/i],
  ['hypovereinsbank', /hypovereinsbank|unicredit/i],
  ['santander', /santander/i],
  ['targobank', /targobank/i],
  ['norisbank', /norisbank/i],
  ['consorsbank', /consorsbank|bnp paribas/i],
  ['apobank', /apotheker|apobank/i],
  ['gls', /\bgls\b/i],
  ['triodos', /triodos/i],
  ['ethikbank', /ethikbank/i],
  ['oldenburgische', /oldenburgische landesbank|\bolb\b/i],
  ['degussa', /degussa/i],
];

function brandOf(name: string): Brand {
  for (const [brand, re] of BRAND_RULES) {
    if (re.test(name)) return brand;
  }
  return 'generic';
}

const institutes: Institute[] = raw.map((b) => ({ ...b, brand: brandOf(b.name) }));

const byBlz = new Map(institutes.map((b) => [b.blz, b]));

// ---------------------------------------------------------------------------
// Search: by BLZ (prefix), by BIC (prefix) or by name/location (word
// matching, diacritic-safe). An IBAN is never searched here: the browser
// reads its BLZ and sends only that (lib/bank-query.ts).
// ---------------------------------------------------------------------------
const normalize = (s: string) =>
  s
    .toLowerCase()
    .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue').replace(/ß/g, 'ss')
    .normalize('NFD').replace(/[̀-ͯ]/g, '');

/**
 * The short names people search by that are in no institute's name: "DKB" is
 * not in "Deutsche Kreditbank Berlin". Keyed by brand, because the brand rules
 * above are tight (dkb is exactly BLZ 120 300 00). "ING-DiBa" needs none — it
 * is the institute's own name.
 */
const ALIASES: Partial<Record<Brand, string>> = {
  dkb: 'dkb',
  hypovereinsbank: 'hvb',
  apobank: 'apobank',
  oldenburgische: 'olb',
};

// Name, town and alias — not the BIC. A BIC read as free text matches inside
// other banks' codes: "DKB" is the end of BYLADEM1DKB, a Sparkasse in
// Dinkelsbühl. BICs are matched from their start only, below.
const searchIndex = institutes.map((b) => ({
  bank: b,
  text: normalize(`${b.name} ${b.location} ${ALIASES[b.brand] ?? ''}`),
  name: normalize(b.name),
  alias: ALIASES[b.brand] ?? null,
}));
type IndexEntry = (typeof searchIndex)[number];

/** A BIC, or the start of one: four letters, then the country (MALADE51KOB). */
const BIC_PREFIX = /^[A-Za-z]{4}[A-Za-z0-9]{0,7}$/;

export function searchBanks(query: string, limit = 25): Institute[] {
  const q = parseBankQuery(query);

  if (q.kind === 'blz') {
    // A BLZ or the beginning of one — spaces between the digits allowed, the
    // way the app prints it ("370 400 44").
    if (!/^\d{3,8}$/.test(q.digits)) return [];
    const exact = byBlz.get(q.digits);
    const prefix = institutes.filter((b) => b.blz.startsWith(q.digits) && b !== exact);
    return [exact, ...prefix].filter((b): b is Institute => !!b).slice(0, limit);
  }
  if (q.kind !== 'text') return [];

  // BIC prefix matches rank before the free-text results, which still follow:
  // "Deut" is the start of a BIC and of a name alike.
  const bicHits: Institute[] = [];
  if (BIC_PREFIX.test(q.text) && q.text.length >= 4) {
    const bq = q.text.toUpperCase();
    bicHits.push(...institutes.filter((b) => b.bic && b.bic.startsWith(bq)));
    bicHits.sort((a, b) => a.bic.localeCompare(b.bic) || a.blz.localeCompare(b.blz));
  }

  const words = normalize(q.text).split(/\s+/).filter(Boolean);
  const nq = words.join(' ');
  const taken = new Set(bicHits);
  const matches: IndexEntry[] = [];
  for (const entry of searchIndex) {
    if (taken.has(entry.bank) || !words.every((w) => entry.text.includes(w))) continue;
    matches.push(entry);
    if (matches.length >= 200) break; // plenty; ranked below
  }
  // Rank: a bank asked for by its short name ("DKB") or a name that starts
  // with the query first, then shorter names (usually the "head" institute),
  // then the BLZ, so rows of one name keep one order.
  const rank = (e: IndexEntry) => ((e.alias && words.includes(e.alias)) || e.name.startsWith(nq) ? 0 : 1);
  matches.sort((a, b) =>
    rank(a) - rank(b) || a.bank.name.length - b.bank.name.length || a.bank.blz.localeCompare(b.bank.blz));
  return [...bicHits, ...matches.map((e) => e.bank)].slice(0, limit);
}

export function lookupBlz(blz: string | undefined | null): Institute | null {
  if (blz == null) return null;
  return byBlz.get(String(blz).trim()) || null;
}

export const bankCount = institutes.length;

// ---------------------------------------------------------------------------
// Curated quick-pick list shown on the login screen.
// Sparkasse/VR entries have no fixed BLZ — the user finds their local institute
// via the search — so the quick picks are the big nationwide banks.
// ---------------------------------------------------------------------------
const PRESETS: PopularBank[] = [
  { key: 'sparkasse', name: 'Sparkasse', brand: 'sparkasse', search: 'Sparkasse' },
  { key: 'vrbank', name: 'Volksbank / VR-Bank', brand: 'vrbank', search: 'Volksbank' },
  { key: 'ing', name: 'ING', brand: 'ing', blz: '50010517' },
  // All of DKB is one BLZ: the tile picks it, rather than searching "DKB".
  { key: 'dkb', name: 'DKB', brand: 'dkb', blz: '12030000' },
  { key: 'commerzbank', name: 'Commerzbank', brand: 'commerzbank', search: 'Commerzbank' },
  { key: 'deutschebank', name: 'Deutsche Bank', brand: 'deutschebank', search: 'Deutsche Bank' },
  { key: 'postbank', name: 'Postbank', brand: 'postbank', search: 'Postbank' },
  { key: 'comdirect', name: 'comdirect', brand: 'comdirect', search: 'comdirect' },
  { key: 'hypovereinsbank', name: 'HypoVereinsbank', brand: 'hypovereinsbank', blz: '70020270' },
  { key: 'targobank', name: 'Targobank', brand: 'targobank', blz: '30020900' },
  { key: 'consorsbank', name: 'Consorsbank', brand: 'consorsbank', blz: '76030080' },
  { key: 'norisbank', name: 'norisbank', brand: 'norisbank', blz: '10077777' },
  { key: 'sparda', name: 'Sparda-Bank', brand: 'sparda', search: 'Sparda' },
  { key: 'psd', name: 'PSD Bank', brand: 'psd', search: 'PSD' },
  { key: 'apobank', name: 'apoBank', brand: 'apobank', blz: '30060601' },
  { key: 'gls', name: 'GLS Bank', brand: 'gls', blz: '43060967' },
];

export const POPULAR_BANKS: PopularBank[] = PRESETS
  .map((p) => {
    if (p.blz) {
      const inst = byBlz.get(p.blz);
      if (!inst) return null; // BLZ not in the current dataset — drop the preset
      return { ...p, url: inst.url, bic: inst.bic, fullName: inst.name };
    }
    return p;
  })
  .filter((p): p is PopularBank => !!p);
