// Bank database: all German FinTS/PIN-TAN institutes.
//
// Source: banks-data.json, generated by scripts/update-banks.mjs from
// hbci4java's actively maintained blz.properties (with dead hosts rewritten
// to their live successors and legacy alternate URLs preserved as urlAlt).
// Re-run the script to refresh. On top of that we detect a "brand" per bank
// group so the frontend can show a matching logo, and expose a curated list
// of popular banks for quick access.

import fs from 'node:fs';
import path from 'node:path';

export type Brand =
  | 'sparkasse' | 'sparda' | 'psd' | 'vrbank' | 'deutschebank' | 'postbank'
  | 'commerzbank' | 'comdirect' | 'ing' | 'dkb' | 'hypovereinsbank' | 'santander'
  | 'targobank' | 'norisbank' | 'consorsbank' | 'apobank' | 'gls' | 'triodos'
  | 'ethikbank' | 'oldenburgische' | 'degussa' | 'generic';

/** One row of banks-data.json, plus the detected brand. */
export type Institute = {
  blz: string;
  name: string;
  location: string;
  bic: string;
  url: string;
  urlAlt?: string;
  brand: Brand;
};

/** A curated login-screen quick pick. */
export type PopularBank = {
  key: string;
  name: string;
  brand: Brand;
  hint: string;
  /** Nationwide banks resolve to one BLZ … */
  blz?: string;
  url?: string;
  bic?: string;
  fullName?: string;
  /** … regional groups (Sparkasse, VR, …) hand over to the search instead. */
  search?: string;
};

type RawInstitute = Omit<Institute, 'brand'>;

const raw: RawInstitute[] = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), 'banks-data.json'), 'utf8'),
);

// ---------------------------------------------------------------------------
// Brand detection — used to pick a logo + accent color in the frontend.
// ---------------------------------------------------------------------------
const BRAND_RULES: [Brand, RegExp][] = [
  ['sparkasse', /sparkasse|kreissparkasse|stadtsparkasse|spk\b/i],
  ['sparda', /sparda/i],
  ['psd', /\bpsd\b/i],
  ['vrbank', /volksbank|raiffeisen|vr[- ]?bank|vr bank|spar- ?u\.? ?kredit|budenheim|genossenschaftsbank|verbund|aachener bank|gladbacher bank|k(ö|oe)lner bank|dortmunder volks/i],
  ['deutschebank', /deutsche bank/i],
  ['postbank', /postbank/i],
  ['commerzbank', /commerzbank/i],
  ['comdirect', /comdirect/i],
  ['ing', /\bing[- ]/i],
  ['dkb', /deutsche kreditbank|\bdkb\b/i],
  ['hypovereinsbank', /hypovereinsbank|unicredit/i],
  ['santander', /santander/i],
  ['targobank', /targobank/i],
  ['norisbank', /norisbank/i],
  ['consorsbank', /consorsbank|bnp paribas/i],
  ['apobank', /apotheker|apobank/i],
  ['gls', /\bgls\b/i],
  ['triodos', /triodos/i],
  ['ethikbank', /ethikbank/i],
  ['oldenburgische', /oldenburgische landesbank|\bolb\b/i],
  ['degussa', /degussa/i],
];

function brandOf(name: string): Brand {
  for (const [brand, re] of BRAND_RULES) {
    if (re.test(name)) return brand;
  }
  return 'generic';
}

const institutes: Institute[] = raw.map((b) => ({ ...b, brand: brandOf(b.name) }));

const byBlz = new Map(institutes.map((b) => [b.blz, b]));

// ---------------------------------------------------------------------------
// Search: by BLZ (prefix) or by name/location (word matching, diacritic-safe).
// ---------------------------------------------------------------------------
const normalize = (s: string) =>
  s
    .toLowerCase()
    .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue').replace(/ß/g, 'ss')
    .normalize('NFD').replace(/[̀-ͯ]/g, '');

const searchIndex = institutes.map((b) => ({ bank: b, text: normalize(`${b.name} ${b.location} ${b.bic}`) }));

export function searchBanks(query: string, limit = 25): Institute[] {
  const q = (query || '').trim();
  if (!q) return [];

  if (/^\d{3,8}$/.test(q)) {
    // Looks like a BLZ (or the beginning of one)
    const exact = byBlz.get(q);
    const prefix = institutes.filter((b) => b.blz.startsWith(q) && b !== exact);
    return [exact, ...prefix].filter((b): b is Institute => !!b).slice(0, limit);
  }

  // Looks like a BIC (or the beginning of one): 4 letters, then country code,
  // e.g. MALADE51KOB. Prefix matches rank before the free-text results.
  if (/^[A-Za-z]{4}[A-Za-z0-9]{0,7}$/.test(q) && q.length >= 4) {
    const bq = q.toUpperCase();
    const bicHits = institutes.filter((b) => b.bic && b.bic.startsWith(bq));
    if (bicHits.length) {
      bicHits.sort((a, b) => a.bic.localeCompare(b.bic) || a.blz.localeCompare(b.blz));
      return bicHits.slice(0, limit);
    }
    // fall through to name search (e.g. "AACH" is a city prefix, not a BIC)
  }

  const words = normalize(q).split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const matches: Institute[] = [];
  for (const { bank, text } of searchIndex) {
    if (words.every((w) => text.includes(w))) {
      matches.push(bank);
      if (matches.length >= 200) break; // plenty; ranked below
    }
  }
  // Rank: name starts with query > shorter names first (usually the "head" institute)
  const nq = normalize(q);
  matches.sort((a, b) => {
    const aStarts = normalize(a.name).startsWith(nq) ? 0 : 1;
    const bStarts = normalize(b.name).startsWith(nq) ? 0 : 1;
    if (aStarts !== bStarts) return aStarts - bStarts;
    return a.name.length - b.name.length;
  });
  return matches.slice(0, limit);
}

export function lookupBlz(blz: string | undefined | null): Institute | null {
  if (blz == null) return null;
  return byBlz.get(String(blz).trim()) || null;
}

export const bankCount = institutes.length;

// ---------------------------------------------------------------------------
// Curated quick-pick list shown on the login screen.
// Sparkasse/VR entries have no fixed BLZ — the user finds their local institute
// via the search — so the quick picks are the big nationwide banks.
// ---------------------------------------------------------------------------
const PRESETS: PopularBank[] = [
  { key: 'sparkasse', name: 'Sparkasse', brand: 'sparkasse', search: 'Sparkasse', hint: 'Deine lokale Sparkasse per BLZ oder Ort suchen · S-pushTAN' },
  { key: 'vrbank', name: 'Volksbank / VR-Bank', brand: 'vrbank', search: 'Volksbank', hint: 'Deine lokale VR-Bank per BLZ oder Ort suchen · SecureGo plus' },
  { key: 'ing', name: 'ING', brand: 'ing', blz: '50010517', hint: 'Banking to go App' },
  { key: 'dkb', name: 'DKB', brand: 'dkb', search: 'DKB', hint: 'Deine BLZ suchen · DKB-App' },
  { key: 'commerzbank', name: 'Commerzbank', brand: 'commerzbank', search: 'Commerzbank', hint: 'Deine BLZ suchen · photoTAN' },
  { key: 'deutschebank', name: 'Deutsche Bank', brand: 'deutschebank', search: 'Deutsche Bank', hint: 'Deine BLZ suchen · photoTAN' },
  { key: 'postbank', name: 'Postbank', brand: 'postbank', search: 'Postbank', hint: 'Deine BLZ suchen · BestSign' },
  { key: 'comdirect', name: 'comdirect', brand: 'comdirect', search: 'comdirect', hint: 'Deine BLZ suchen · photoTAN' },
  { key: 'hypovereinsbank', name: 'HypoVereinsbank', brand: 'hypovereinsbank', blz: '70020270', hint: 'appTAN' },
  { key: 'targobank', name: 'Targobank', brand: 'targobank', blz: '30020900', hint: 'easyTAN' },
  { key: 'consorsbank', name: 'Consorsbank', brand: 'consorsbank', blz: '76030080', hint: 'SecurePlus' },
  { key: 'norisbank', name: 'norisbank', brand: 'norisbank', blz: '10077777', hint: 'photoTAN' },
  { key: 'sparda', name: 'Sparda-Bank', brand: 'sparda', search: 'Sparda', hint: 'Deine lokale Sparda-Bank suchen · SpardaSecureApp' },
  { key: 'psd', name: 'PSD Bank', brand: 'psd', search: 'PSD', hint: 'Deine lokale PSD Bank suchen' },
  { key: 'apobank', name: 'apoBank', brand: 'apobank', blz: '30060601', hint: 'apoTAN' },
  { key: 'gls', name: 'GLS Bank', brand: 'gls', blz: '43060967', hint: 'SecureGo plus' },
];

export const POPULAR_BANKS: PopularBank[] = PRESETS
  .map((p) => {
    if (p.blz) {
      const inst = byBlz.get(p.blz);
      if (!inst) return null; // BLZ not in the current dataset — drop the preset
      return { ...p, url: inst.url, bic: inst.bic, fullName: inst.name };
    }
    return p;
  })
  .filter((p): p is PopularBank => !!p);
